export const ROOT_PATH = "/"
export const ADMIN_PATH = "/admin"
export const USER_PATH = "/user"
export const AUTHEN_PATH = "/user/account"
export const SIGN_IN_PATH = "/user/account/signin"
export const SIGN_UP_PATH = "/user/account/signup"
export const DETAIL_MOVIE_PATH = "/user/movie/:id"
export const ORDER_PATH = "/user/order/:id"

export const GET_BANNER = "/banner"
export const GET_ORDER = "/order"
export const GET_EVENTS = "/events"
export const GET_MOVIES = "/movies"
export const GET_CALENDAR = "/calendar"

export const PUSH_ORDER = "./ordered"
